version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samsung_smartlab_api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./.env.docker:/var/www/html/.env
    ports:
      - "${APP_PORT:-3500}:3500"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-samsungsmartlab}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
    depends_on:
      - mysql
      - redis
    networks:
      - samsung_smartlab_network

  mysql:
    image: mysql:8.0
    container_name: samsung_smartlab_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-samsungsmartlab}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-root}
    ports:
      - "${DB_PORT:-3308}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - samsung_smartlab_network

  redis:
    image: redis:7-alpine
    container_name: samsung_smartlab_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - samsung_smartlab_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  samsung_smartlab_network:
    driver: bridge 